### ISSUE TITLE
type field (MySQL?)

### ISSUE THREAD

**Issue by odilitime** [biggora/caminte#136]
Using the MySQL driver, tried to store data in a field called type and I got an SQL error

Please either document that you can't use type in fields or fix

Error: ER_BAD_FIELD_ERROR: Unknown column 'net_app_alpha_attachment' in 'field list'
    at Query.Sequence._packetToError (/tank/Users/rtharp/Sites/adn/AppDotNetAPI/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/tank/Users/rtharp/Sites/adn/AppDotNetAPI/node_modules/mysql/lib/protocol/sequences/Query.js:82:18)
    at Protocol._parsePacket (/tank/Users/rtharp/Sites/adn/AppDotNetAPI/node_modules/mysql/lib/protocol/Protocol.js:271:23)
    at Parser.write (/tank/Users/rtharp/Sites/adn/AppDotNetAPI/node_modules/mysql/lib/protocol/Parser.js:77:12)
    at Protocol.write (/tank/Users/rtharp/Sites/adn/AppDotNetAPI/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/tank/Users/rtharp/Sites/adn/AppDotNetAPI/node_modules/mysql/lib/Connection.js:82:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)

**Comment by odilitime** [comment]
ah the column type was wrong
