### ISSUE TITLE
TypeError: Cannot read property 'default' of undefined

### ISSUE THREAD

**Issue by SashaDesigN** [biggora/caminte#188]
my model file:
```
module.exports = (schema) => {
    var Messages = schema.define('messages', {
        user_id: { type: schema.Number, limit: 10 },
        message: { type: schema.String, limit: 5000 }
    }, {
    });
    return Messages;
};
```
My code:
```
schema.Messages.find({'is_active': 1}, (err, accounts) => {
...
});
```
It issuing this:
```
/var/www/linkedin/node_modules/caminte/lib/abstract-class.js:150
        var def = properties[attr]['default'];
                                  ^
TypeError: Cannot read property 'default' of undefined
    at getDefault (/var/www/linkedin/node_modules/caminte/lib/abstract-class.js:150:35)
    at /var/www/linkedin/node_modules/caminte/lib/abstract-class.js:124:56
    at Array.forEach (native)
    at Function.NewClass.forEachProperty (/var/www/linkedin/node_modules/caminte/lib/schema.js:261:33)
    at ModelConstructor.AbstractClass._initProperties (/var/www/linkedin/node_modules/caminte/lib/abstract-class.js:122:10)
    at ModelConstructor.AbstractClass (/var/www/linkedin/node_modules/caminte/lib/abstract-class.js:69:10)
    at new ModelConstructor (/var/www/linkedin/node_modules/caminte/lib/schema.js:219:23)
    at /var/www/linkedin/node_modules/caminte/lib/abstract-class.js:512:31
    at Array.forEach (native)
    at /var/www/linkedin/node_modules/caminte/lib/abstract-class.js:511:22
    at MySQL.<anonymous> (/var/www/linkedin/node_modules/caminte/lib/adapters/mysql.js:481:9)
    at Query._callback (/var/www/linkedin/node_modules/caminte/lib/adapters/mysql.js:158:20)
    at Query.Sequence.end (/var/www/linkedin/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Query._handleFinalResultPacket (/var/www/linkedin/node_modules/mysql/lib/protocol/sequences/Query.js:139:8)
    at Query.EofPacket (/var/www/linkedin/node_modules/mysql/lib/protocol/sequences/Query.js:123:8)
    at Protocol._parsePacket (/var/www/linkedin/node_modules/mysql/lib/protocol/Protocol.js:279:23)

```

**Comment by SashaDesigN** [comment]
I found why it happen!) I just define model in other file with the same name, so it overwrite each other. When I made each schema.define('uniqueNameThere') unique it back to normal work. 
Just create this issue to do help if anyone will have the same)
