### ISSUE TITLE
error  using caminte -i -a mysql

### ISSUE THREAD

**Issue by Level0r0s** [biggora/caminte#210]
caminte -i -a mysql
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/caminte-cli/bin/../templates/Model.ejs'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/caminte-cli/bin/caminte:60:14)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)

**Comment by Level0r0s** [comment]
replaced Model.ejs   to model.ejs 
ok

**Comment by Level0r0s** [comment]
caminte -i -a mysql

destination is not empty, continue? [y/N] y
   Add the following strings
   to your express app.js:
   
   var models = require('./models');
   models.init(app);
   
   
fs.js:128
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:128:9)
    at Object.writeFile (fs.js:1163:14)
    at write (/usr/local/lib/node_modules/caminte-cli/bin/caminte:743:8)
    at /usr/local/lib/node_modules/caminte-cli/bin/caminte:647:13
    at /usr/local/lib/node_modules/caminte-cli/node_modules/async/dist/async.js:3888:9
    at /usr/local/lib/node_modules/caminte-cli/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/usr/local/lib/node_modules/caminte-cli/node_modules/async/dist/async.js:1064:13)
    at /usr/local/lib/node_modules/caminte-cli/node_modules/async/dist/async.js:969:16
    at /usr/local/lib/node_modules/caminte-cli/node_modules/async/dist/async.js:3885:13
    at /usr/local/lib/node_modules/caminte-cli/bin/caminte:764:26
