### ISSUE TITLE
Finding objects from relations/setup relations

### ISSUE THREAD

**Issue by thibautrey** [biggora/caminte#51]
Hi everyone,

I have been trying 2 for days to figure the way the relations work with Caminte and I can't figure out. 

I have the following Models : 
```
var Class1 = schema.define(className, {
    objectId          : { type: schema.String, unique: true, index: true },
    createdAt         : { type: schema.Date,                 index: true },
    updatedAt         : { type: schema.Date,                 index: true }
}, {
    primaryKeys: ["objectId"]
});

///// RELATIONS /////
Class1.hasMany(Class2,  {as: 'otherclasses',  foreignKey: "objectId"});

var Class2 = schema.define(className, {
    objectId          : { type: schema.String, unique: true, index: true },
    createdAt         : { type: schema.Date,                 index: true },
    updatedAt         : { type: schema.Date,                 index: true }
}, {
    primaryKeys: ["objectId"]
});
```

I would like to be able to query all the objects in "otherclasses".
I'm trying this way : but obviously it doesn't sound to be the right way :
``` 
var query = instanceOfClass1.otherclasses.find();
      query.limit(10);
      query.run({}, function(err, results){
      });
```

Can anyone help me out with that ?

Adapter : REDIS
Error thrown : 

```
TypeError: undefined is not a function
    at ModelConstructor.<anonymous> (node_modules/caminte/lib/abstract-class.js:1117:24)
    at Function.<anonymous> (node_modules/caminte/lib/abstract-class.js:455:9)
    at BridgeToRedis.<anonymous> (node_modules/caminte/lib/adapters/redis.js:390:9)
    at node_modules/caminte/lib/adapters/redis.js:85:25
    at node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (node_modules/redis/index.js:321:14)
    at ReplyParser.EventEmitter.emit (events.js:95:17)
    at ReplyParser.send_reply (node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (node_modules/redis/lib/parser/javascript.js:211:22)
```

**Comment by biggora** [comment]
Hi,
At first in that case use `hasMany` is incorrect. `hasMany` is relation one record in Class1 for many records in Class2 via `foreignKey`. But in your example `objectId` defined as unique key in both clesses. For this case use `belongsTo`.
At second query interface not work for relations.

**Comment by inazrabuu** [comment]
Hello,

So what is the proper way to select data with the relationship as above?

I have the same problem here, can't figure it out on how to select the data.

this is my schema:
```
const BrandUpdate = schema.define('nubr_brands_update', {
	nbu_id: schema.Number,
	nbu_brand_id: schema.Number,
	nbu_name: schema.Text,
	nbu_image: schema.Text,
	nbu_url: schema.Text,
	nbu_created_at: schema.Date,
	nbu_created_by: schema.Number,
	nbu_updated_at: schema.Date,
	nbu_updated_by: schema.Number
}, {
	primaryKeys: ['nbu_id']
})

const Brand = schema.define('nubr_brands', {
	brands_id: schema.Number,
	brands_item: schema.Text,
	brands_slug: schema.Text,
	brands_desc: schema.Text,
	brands_meta_desc: schema.Text,
	brands_braori_id: schema.Number,
	brands_total_product: schema.Number,
	brands_total_review_num: schema.Number,
	brands_rating: schema.Float,
	brands_price: schema.Float,
	brands_frontend: schema.Text,
	brands_sort_frontend: schema.Text,
	brands_size_lg: schema.Text,
	brands_size_md: schema.Text,
	brands_size_sm: schema.Text,
	brands_size_vsm: schema.Text,
	brands_view: schema.Number,
	brands_prod_view: schema.Number,
	brands_prod_app_view: schema.Number,
	brands_create_date: schema.Date,
	brands_status: schema.Text,
	status_elastic: schema.Text,
	brands_top: schema.Text
},{
	primaryKeys: ['brands_id']
})
```

here is the relationship 
```
BrandUpdate.belongsTo(Brand, {as: 'brand', foreignKey: 'brands_id'})
```

how can I access the Brand from BrandUpdate and the other way around?

I tried this:
```
BrandUpdate.all((err, bus) => {
		for (bu in bus){
			console.log(bu.brand)
		}
	})

```
doesn't work

Please enlighten me :(
