### ISSUE TITLE
Redis allows duplicate entries on a unique column

### ISSUE THREAD

**Issue by BrandonEstockCTI** [biggora/caminte#54]
When I defined a model with the property 'email' which should be unique, I was able to create multiple entries that had the same value with no errors.

My model definition looks like this
```
var Model = schema.define('Model', {
    email: { type: schema.String, "null": false, unique: true, index: true }
});
```

I am creating the instances like this
```
var model = new Model({ email: "jdoe@example.com" });
model.save(function (err) {
    err == null;  //true
});
```

After doing the above twice, I query all entries like this
```
Model.all().run({}, function (err, results) {
    err == null;  
    results == [
        { email: 'jdoe@conferencetech.com', id: 1 },
        { email: 'jdoe@conferencetech.com', id: 2 }
    ]; 
});
```

Unless there is a different way to specify a property as unique, this seems broken.

**Comment by biggora** [comment]
Hi,
If you need unique field for radis adapter, please use custom async validation.
[docs here](https://github.com/biggora/caminte/wiki/Setup-Relationships-&-Validations#custom-validations)
example:
```js
/* define model */
var User = schema.define('User', {
    email:       { type: schema.String,  limit: 150 },,
    name:       { type: schema.String,  limit: 250 },,
    bio:           { type: schema.Text },,
    approved: { type: schema.Boolean, default: false },
    joinedAt:   { type: schema.Date,    default: Date.now },
    age:          { type: schema.Number, default: 0 }
});

/* custom validator */
function emailValidator(err, done) {
     User.findOne( { email : this.email }).exec(function (e,u) {
          if (u) { err(); }
          done();
      });
});

/* define validations */
User.validatesLengthOf('email', {min: 3, max: 150 , message: {min: 'is too short', max: 'is too long'}});
User.validatesLengthOf('name', {min: 2, max: 250 , message: {min: 'is too short', max: 'is too long'}});
/* custom validation */
User.validateAsync('email', emailValidator, {message: 'is duplicate'});

var user = new User ({ email: "jdoe@example.com", name: 'Jdoe' });
user.isValid(function (isValid) {
       if(isValid) {
           user.save(function (err) {
                  if(err) { return console.log('user create err:', err);  }
                  console.log('user created'); 
             });
       } else {
           console.log('user validation error:', user.errors); 
       }
 });

```

**Comment by penguinpowernz** [comment]
Hey dude, when trying your example 2 above I get this error whenever I try to get a record:

```
/home/robert/src/phoenix/api/node_modules/caminte/lib/adapters/redis.js:591
            throw new Error(model + ': no indexes found for ' +
                  ^
Error: reading: no indexes found for address impossible to sort and filter using redis adapter
    at /home/robert/src/phoenix/api/node_modules/caminte/lib/adapters/redis.js:591:19
    at BridgeToRedis.possibleIndexes (/home/robert/src/phoenix/api/node_modules/caminte/lib/adapters/redis.js:553:9)
    at BridgeToRedis.all (/home/robert/src/phoenix/api/node_modules/caminte/lib/adapters/redis.js:580:10)
    at Function.all (/home/robert/src/phoenix/api/node_modules/caminte/lib/abstract-class.js:496:31)
    at Function.findOne (/home/robert/src/phoenix/api/node_modules/caminte/lib/abstract-class.js:541:18)
    at Query.self.(anonymous function) [as exec] (/home/robert/src/phoenix/api/node_modules/caminte/lib/query.js:42:31)
    at ModelConstructor.addressValidator (/home/robert/src/phoenix/api/models/Reading.js:22:48)
    at ModelConstructor.validateCustom (/home/robert/src/phoenix/api/node_modules/caminte/lib/validatable.js:301:26)
    at validationFailed (/home/robert/src/phoenix/api/node_modules/caminte/lib/validatable.js:475:15)
    at /home/robert/src/phoenix/api/node_modules/caminte/lib/validatable.js:385:17
```

It also does not work when saving, as every save operation returns an error (400 bad request).

This is the model:

```js
module.exports = function(schema){
    var Reading = schema.define('reading', {
           address :   { type : schema.String, unique: true },
           timestamp : { type : schema.Date },
           data :      { type : schema.Json }
    });

    // this didn't work either
    //Reading.validatesUniquenessOf('address', {message: 'not unique'});

    var addressValidator = function(err, done) {
      Reading.findOne({address: this.address}).exec(function (e,u) {
        if (u) { err(); }
        done();
      });
    };

    Reading.validateAsync('address', addressValidator, {message: 'is not unique'});

    return Reading;
};
```
