### ISSUE TITLE
insert data inside callback of another insert not working

### ISSUE THREAD

**Issue by rajkumarpb** [biggora/caminte#87]
So I'm trying to do Login.create inside User.create and getting the below error.

    \node_modules\mysql\lib\protocol\Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

    TypeError: Cannot read property 'constructor' of undefined
    at MySQL.toDatabase (\node_modules\caminte\lib\adapters\mysql.js:347:12)
    at MySQL.<anonymous> (\node_modules\caminte\lib\adapters\mysql.js:321:73)
    at Array.forEach (native)
    at MySQL.toFields (\node_modules\caminte\lib\adapters\mysql.js:319:23)
    at MySQL.create (\node_modules\caminte\lib\adapters\mysql.js:261:23)
    at ModelConstructor.<anonymous> (\node_modules\caminte\lib\abstract-class.js:256:29)
    at ModelConstructor.trigger (\node_modules\caminte\lib\hookable.js:34:18)
    at create (\node_modules\caminte\lib\abstract-class.js:251:13)
    at Function.AbstractClass.create (\node_modules\caminte\lib\abstract-class.js:236:9)
    at \routes\auth.js:128:12

Code block 

    User.find({where: {api_id: profile.id}}, function(err, data){   		
   		if(err !== null) {
   			User.create(user, function(err, data){
   				//console.log(data);
   				//console.log(err);
				if(err === null) {
					var login = new Login({
						user_id : data.id, 
						username : profile.name.displayName,
						password : '',
						login_type : 'local',
						is_active : 'Y',
						registered_at : new Date()
					});
					Login.create(login, function(err, data){
						console.log(err);
						if(err!==null)
							res.render('index', { title: 'Valid User' });
						else
							res.render('index', { title: 'Not Valid' });
					});				
				}
			});
   		}
	});

Can someone help me what is wrong? I couldn't find where I did mistake. Help appreciated

**Comment by rajkumarpb** [comment]
Any help guys?

**Comment by rajkumarpb** [comment]
Well, moved to node-orm2 and had this finished up in a jiffy!! Still can't believe such a good potential ORM has got no active contribution! Closing this issue.

**Comment by SashaDesigN** [comment]
I had the same issue and it's because I pass invalid data for saving, after I fix the data all works well.
